# Pod Yaml file
# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp
#   labels:
#     name: myapp
# spec:
#   containers:
#   - name: myapp
#     image: myappimage
#     resources:
#       limits:
#         memory: "128Mi"
#         cpu: "500m"
#     ports:
#       - containerPort: 8080

# Servvice Yaml file
# apiVersion: v1
# kind: Service
# metadata:
#   name: myservice
# spec:
#   selector:
#     app: myapp
#   ports:
#     - protocol: TCP
#       port: 80
#       targetport : 8000 
#   type: ClusterIP

#